### ISSUE TITLE
Gatekeeper cannot get OpenID configuration

### ISSUE THREAD

**Issue by abstractj** [louketo/louketo-proxy#576]
## What: 

  I'm trying to use Gatekeeper to protect an application. I'm getting the error shown below in the log output:
  
  1.5804951742046025e+09	info	starting the service	{"prog": "keycloak-gatekeeper", "author": "Keycloak", "version": "7.0.0 (git+sha: f66e137, built: 03-09-2019)"}
  
  1.58049517420485e+09	info	attempting to retrieve configuration discovery url	{"url": "https://login.citygate.io/auth/realms/master", "timeout": "30s"}
  
  1.580495184205164e+09	warn	failed to get provider configuration from discovery	{"error": "Get https://login.citygate.io/auth/realms/master/.well-known/openid-configuration: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}
  
  My Gatekeeper configuration looks like this:
  {{discovery-url: https://login.citygate.io/auth/realms/master}}
  {{client-id: docker-admin}}
  {{client-secret: <REDACTED>}}
  {{listen: :80}}
  {{enable-refresh-tokens: true}}
  {{redirection-url: https://docker-admin.citygate.io}}
  {{encryption-key: <REDACTED>}}
  {{upstream-url: http://app:5000}}
  {{resources:}}
  {{- uri: /*}}
  {{methods:}}
  {{- GET}}
  {{- POST}}
  {{roles:}}
  {{- admin}}

## Reference:

- [KEYCLOAK-12866 - Gatekeeper cannot get OpenID configuration](https://issues.redhat.com/browse/KEYCLOAK-12866)

**Comment by luketainton** [comment]
Hi @abstractj,

Thanks for migrating this issue! I did work around this problem by manually creating an `nsswitch.conf` file and bind mounting it inside the container at `/etc/nsswitch.conf` - file contents are below.

```
hosts: files dns
```

I assume this forces it to look at `/etc/hosts` first, which is the desired behaviour because I had used the `extra_hosts` option in `docker-compose.yml` to manually set the IP for my Keycloak server.

Hope this helps!

**Comment by abstractj** [comment]
Thanks for reporting it back. For now I'm closing this issue, as this seems more like a Docker configuration issue, instead of an issue on Louketo.

@ASzc maybe the introduction of `nsswitch.conf` is something that we can take into consideration for #609 to prevent issues like this. But I will leave that up to you.

**Comment by ASzc** [comment]
In #638, with UBI, there will be a `/etc/nsswitch.conf` file present in the image. It's host line is the following:

    hosts:      files dns myhostname

Which I think is acceptable as far as this issue goes, so no further action is required, unless in the future we go to `scratch` or similar options.

**Comment by TcaManager** [comment]
Hi, I have a similar problem with Bitnami Image here https://github.com/bitnami/bitnami-docker-keycloak-gatekeeper/issues/11 so I'm trying Louketo too, but same problem appears.
My docker-compose.yml file.

```yml
version: '3.7'

services:
  postgres:
    image: postgres
    volumes:
      - type: bind
        source: ../postgres_data
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Pa55w0rd
    ports:
      - 5432:5432
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'pgadmin4@pgadmin.org'
      PGADMIN_DEFAULT_PASSWORD: 'Pa55w0rd'
    volumes:
      - type: bind
        source: ../pgadmin_data
        target: /var/lib/pagadmin
    ports:
      - 5050:80
    restart: unless-stopped
    depends_on:
      - postgres
  ldap:
    image: i2hm/openldap:latest
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_SCHEMA: public
      DB_PASSWORD: Pa55w0rd
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - postgres
  louketo-proxy:
    image: quay.io/louketo/louketo-proxy:latest
    command: >-
      --config /opt/louketo/config.yml
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ../gatekeeper/config.yml
        target: /opt/louketo/config.yml
    depends_on:
      - keycloak
      - web
  web:
    build: .
    volumes:
      - type: bind
        source: ../gunicorn_log
        target: /var/log
    ports:
      - 5000:5000
    expose:
      - 5000
    depends_on:
      - postgres
```

My config file.

```yml
client-id: flask_example
client-secret: 7216c35c-0f0a-4dbf-adc8-beb0dc933f27
discovery-url: http://keycloak:8080/auth/realms/identite
enable-default-deny: true
listen: :3000
upstream-url: http://web:5000
resources:
- uri: /admin*
  methods:
  - GET
  roles:
  - client:test1
  - client:test2
  require-any-role: true
  groups:
  - admins
  - users
- uri: /backend*
  roles:
  - client:test1
- uri: /public/*
  white-listed: true
- uri: /favicon
  white-listed: true
- uri: /css/*
  white-listed: true
- uri: /img/*
  white-listed: true
headers:
  myheader1: value_1
  myheader2: value_2
```
I get this error.

```bash
louketo-proxy_1  | 2020-08-20T12:32:14.829Z	info	attempting to retrieve configuration discovery url	{"url": "http://keycloak:8080/auth/realms/identite", "timeout": "30s"}
louketo-proxy_1  | 2020-08-20T12:32:14.835Z	warn	failed to get provider configuration from discovery	{"error": "Get \"http://keycloak:8080/auth/realms/identite/.well-known/openid-configuration\": dial tcp: lookup keycloak on 127.0.0.11:53: no such host"}
louketo-proxy_1  | 2020-08-20T12:32:17.835Z	info	attempting to retrieve configuration discovery url	{"url": "http://keycloak:8080/auth/realms/identite", "timeout": "30s"}
louketo-proxy_1  | 2020-08-20T12:32:17.848Z	warn	failed to get provider configuration from discovery	{"error": "Get \"http://keycloak:8080/auth/realms/identite/.well-known/openid-configuration\": dial tcp: lookup keycloak on 127.0.0.11:53: no such host"}
```
Thanks for your help. Sorry for posting here and at bitnami too.

**Comment by luketainton** [comment]
Hi @TcaManager ,

I had to add the `extra_hosts` directive to my config to overcome this. You'll want something like this:

```yaml
louketo-proxy:
    image: quay.io/louketo/louketo-proxy:latest
    command: >-
      --config /opt/louketo/config.yml
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ../gatekeeper/config.yml
        target: /opt/louketo/config.yml
    depends_on:
      - keycloak
      - web
    extra_hosts:
      - "keycloak:X.X.X.X"

Swap `X.X.X.X` for the internal or external IP address of the Keycloak server.
```

**Comment by TcaManager** [comment]
> ```yaml
> extra_hosts:
>       - "keycloak:X.X.X.X"
> ```

Interesting @luketainton , thanks for your help. What do you mean with internal/external IP address? Do I need to get any ifconfig docker interface IP? My host has many FQDN and IPs in /etc/hosts but I'm on Linux and I wonder which IP would my container use to reach the host? I saw docker0 in ifconfig and many interfaces br-9e188c5db690 (br for bridge?)

**Comment by luketainton** [comment]
> > ```yaml
> > extra_hosts:
> >       - "keycloak:X.X.X.X"
> > ```
> 
> Interesting @luketainton , thanks for your help. What do you mean with internal/external IP address? Do I need to get any ifconfig docker interface IP? My host has many FQDN and IPs in /etc/hosts but I'm on Linux and I wonder which IP would my container use to reach the host? I saw docker0 in ifconfig and many interfaces br-9e188c5db690 (br for bridge?)

Is your Keycloak container accessible from other hosts? If so, it'll be the IP address of the host. Otherwise try copying the `depends_on` section but renaming it to `links`, then remove the `extra_hosts` section.

**Comment by luketainton** [comment]
@TcaManager it'll be whatever the address is on the NIC that represents that particular Docker network - you can run `docker inspect <NAME>`, which will tell you the details (inc. IP address) of the container that you specify. 

Otherwise, you can try this instead:
```yaml
louketo-proxy:
    image: quay.io/louketo/louketo-proxy:latest
    command: >-
      --config /opt/louketo/config.yml
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ../gatekeeper/config.yml
        target: /opt/louketo/config.yml
    depends_on:
      - keycloak
      - web
    links:
      - keycloak
      - web
```
