### ISSUE TITLE
Resource doesn't match # in URI

### ISSUE THREAD

**Issue by zhertig** [louketo/louketo-proxy#614]
We are trying to use gatekeeper to authenticate requests to the kibana GUI. The problem is the kibana endpoints include # in their uris. I.e:

**Comment by zhertig** [comment]
We are trying to use gatekeeper to authenticate requests to the Kibana GUI. The problem is the kibana endpoints include # in their uris. I.e:
```
/app/kibana#/discover
/app/kibana#/visualize
/app/kibana#/dashboards
/app/canvas#
```

As a result I've created uris with gatekeeper to match these endpoints:
```
- uri: /app/kibana#/discover*
  methods:
  - GET
  roles:
  - zack
- uri: /app/kibana#/visualize*
  methods:
  - GET
  roles:
  - john
```

However they are never utilized, I believe because gatekeeper is unable to match the #.

This means I can only restrict access to the root uri up to /app/kibana which is not fine grained enough to restrict different users to different endpoints. 

Perhaps this is supported and I am missing something with the configuration but I've had success locking down endpoints of my own service that does not include any # in the path.
