### ISSUE TITLE
Error using Client Authenticator "Sign Jwt with Client Secret"

### ISSUE THREAD

**Issue by robertoyoc** [louketo/louketo-proxy#622]
Hi, I got the proxy running with the Client Authenticator: "Client Id and Secret" in Keycloak admin console but the app I'm trying to connect with Keycloak needs the JWT to be signed only with the secret. I changed the client Authenticator to Sign Jwt with Client Secret.

Running a `POST /localhost:3000/oauth/login` I got a 500 response. 

Proxy logs:
```
error   unable to request the access token via grant_type 'password'    {"client_ip": "172.29.0.1:50854", "error": "invalid_client: Parameter client_assertion_type is missing"}
```

Tried to search for `client_assertion_type is missing` but did't find anything about it.

I'm running the proxy into a docker-compose file:

```
version: "3"
services:

    keycloak-gatekeeper:
        image: local-louketo-proxy
        volumes:
            - ./conf:/opt/louketo/keycloak-gatekeeper/conf:Z
        command: /keycloak-gatekeeper --config /opt/louketo/keycloak-gatekeeper/conf/config.yaml
        ports: 
            - "3000:3000"
            - "8081:80"
            
        networks: 
            proxy-net:

networks: 
    proxy-net:
        external: 
            name: keycloak_keycloak_server 
```

I'm using a local image because `docker run -it --rm quay.io/louketo/louketo-proxy` is giving me a 403 error on pulling.

My config file inside a my local `conf` folder:
```
client-id: jitsi
client-secret: a_secret
discovery-url: http://keycloak:8080/auth/realms/a_realm
listen: :3000
enable-default-deny: true
enable-login-handler: true
redirection-url: https://127.0.0.1:3000
upstream-url: http://127.0.0.1:80
resources:
- uri: /admin*
  white-listed: true
- uri: /backend*
  white-listed: true
- uri: /public/*
  white-listed: true
- uri: /favicon
  white-listed: true
- uri: /css/*
  white-listed: true
- uri: /img/*
  white-listed: true
```

Keycloak server and proxy are running on the same docker network.
Both, client and realm, exists on my keycloak server.

Am I missing a key concept on Proxy's functionality?

Thanks in advance.
