### ISSUE TITLE
Don't send basic auth header

### ISSUE THREAD

**Issue by vasilievs** [louketo/louketo-proxy#679]
i want to use oauth proxy for kibana authentication.
They are covered by Basic Authentication (i cannot turn it off). 
but,  I want to pass a header 
(in nginx or curl I do this: 
proxy_set_header Authorization "Basic bmdpbng6c2VjcmV0cGFzc3dvcmQ =") 
and it works.

when trying to specify a custom header in a command block:
```
version: '2.4'
services:
  proxy:
    container_name: kibana-proxy
    image: {{ kibana_proxy_image_version }}
    command:
    - --discovery-url={{kibana_proxy_auth_url}}
    - --client-id={{kibana_proxy_clientd_id}}
    - --client-secret={{kibana_proxy_clientd_secret}}
    - --listen=: {{kibana_port}}
    - --redirection-url=https: // {{ansible_fqdn}}: {{kibana_port}}
    - --upstream-url=http: //127.0.0.1: {{kibana_internal_port}}
    - --headers="Basic bmdpbng6c2VjcmV0cGFzc3dvcmQ ="
```

I get an error

>  [error] invalid tag '"Authorization = Basic bmdpbng6c2VjcmV0cGFzc3dvcmQ ="' should be key = pair
> Is this a bug or I cannot pass this header through louketo-proxy?

## Environment
Version of everything that it's running in your environment:
- OS: rhel
docker compose, 
docker image :quay.io/louketo/louketo-proxy
